### ISSUE TITLE
configure failed on Macos Mojave

### ISSUE THREAD

**Issue by moshix** [wrljet/hercules-helper#14]
I am running it with hombrew:

08:33:52~/hercules-helper ./hyperion-buildall.sh --homebrew
Bash version < v4
    Homebrew is already installed
    MacPorts is not installed

Using logfile: hyperion-buildall-2021-08-28-1.log
Creating build cmds file: /Users/moshe/hercules-helper/build-commands-2021-08-28-1.log
Script version: ./hyperion-buildall.sh: v0.9.6-34-g286c960

Config file: ./hercules-helper.conf

General Options:
  --trace         : false
  --verbose       : true
  --prompts       : false
  --sudo          : false
  --homebrew      : true
  --detect-only   : false
  --no-packages   : false
  --no-rexx       : false
  --no-gitclone   : false
  --no-bldlvlck   : false
  --no-autogen    : true
  --no-configure  : false
  --no-clean      : false
  --no-make       : false
  --no-tests      : false
  --no-install    : false
  --no-setcap     : false
  --no-envscript  : false
  --no-bashrc     : false

System information:
  uname -a        : Darwin mac13-2.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
  uname -m        : x86_64
  uname -p        : i386
  uname -s        : Darwin

System detection:
OS Type          : Darwin
Machine Arch     : x86_64
VERSION_ID       : darwin
VERSION_STR      : 10.14.6
VERSION_MAJOR    : 10
VERSION_MINOR    : 14
VERSION_BUILD    : 6
Apple macOS version 10.14.6 (Mojave) found

Search Path      : /Users/moshe/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin

Build tools versions:
  autoconf       : autoconf (GNU Autoconf) 2.71
  automake       : automake (GNU automake) 1.16.3
  libtool        : unknown
  m4             : xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  make           : xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  compiler       : xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  linker         : xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Configuration:
OPT_BUILD_DIR        : /Users/moshe/hercules-helper
OPT_INSTALL_DIR      : /Users/moshe/hercules-helper/herc4x
OPT_REGINA_DIR       : Regina-REXX-3.6
OPT_REGINA_TARFILE   : Regina-REXX-3.6.tar.gz
OPT_REGINA_URL       : http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz
GIT_REPO_HYPERION    : https://github.com/wrljet/hyperion.git [default branch]
GIT_REPO_GISTS       : https://github.com/SDL-Hercules-390/gists.git [default branch]
GIT_REPO_EXTPKGS     : https://github.com/SDL-Hercules-390 [default branch]

Performing Steps:
run  : Check for required system packages
run  : Build Regina REXX
run  : Git clone Hercules and external packages
skip : Run bldlvlck
run  : Build Hercules external packages
skip : Run autogen
run  : Run configure
run  : Run make clean
run  : Run make (compile and link)
run  : Run make check
run  : Run make install
run  : setcap executables
run  : Create script to set environment variables
run  : Add setting environment variables from .bashrc

Step: Check for required packages:

[[ note: ]] Note: your sudo password may be requested

Required packages: 
wget autoconf automake libtool cmake gsed

-----------------------------------------------------------------
Checking for package: wget
package: wget is already installed
-----------------------------------------------------------------
Checking for package: autoconf
package: autoconf is already installed
-----------------------------------------------------------------
Checking for package: automake
package: automake is already installed
-----------------------------------------------------------------
Checking for package: libtool
package: libtool is already installed
-----------------------------------------------------------------
Checking for package: cmake
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
package: cmake is already installed
-----------------------------------------------------------------
Checking for package: gsed
package: gsed is already installed

Step: Check REXX and compiler files:

REXX presence    : /usr/local/bin/rexx
Checking for Regina-REXX...  
Found REXX       : REXX-Regina_3.9.3 5.00 5 Oct 2019 (64 bit)
Regina version   : 3.9
cc_status = 1
[[ error: ]] rexxsaa.h is not found in cc search path
++ 
Checking for ooRexx... nope
Found REXX, but not ooRexx
CC               : cc
CFLAGS           : 
CPPFLAGS         : 
LDFLAGS          : 
gcc presence     : /usr/bin/gcc
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
cc              : 
g++ presence     : /usr/bin/g++
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
looking for files ... please wait ...
cc1 presence     : skipped on macOS
cc1plus presence : skipped on macOS

Processing started: Sat Aug 28 08:34:16 CEST 2021
-----------------------------------------------------------------

Regina REXX is present.  Skipping build from source.
-----------------------------------------------------------------

Step: git clone all required repos:

git clone https://github.com/wrljet/hyperion.git
Cloning into 'hyperion'...
^[[B^[[A
Cloning gists / extpkgs from https://github.com/SDL-Hercules-390/gists.git
git clone https://github.com/SDL-Hercules-390/gists.git
Cloning into 'gists'...

-----------------------------------------------------------------
    
git clone https://github.com/SDL-Hercules-390/crypto crypto-0
Cloning into 'crypto-0'...
-----------------------------------------------------------------
    
git clone https://github.com/SDL-Hercules-390/decNumber decNumber-0
Cloning into 'decNumber-0'...
-----------------------------------------------------------------
    
git clone https://github.com/SDL-Hercules-390/SoftFloat SoftFloat-0
Cloning into 'SoftFloat-0'...
-----------------------------------------------------------------
    
git clone https://github.com/SDL-Hercules-390/telnet telnet-0
Cloning into 'telnet-0'...
-----------------------------------------------------------------

Skipping step: util/bldlvlck (--no-bldlvlck)
-----------------------------------------------------------------

Step: Prepare and build extpkgs:

Defaulting to x86 machine type in extpkgs.sh.ini

cmdline = extpkgs.sh c d s t

action         =  BUILD
crypto_repo    = "/Users/moshe/hercules-helper/extpkgs/repos/crypto-0"
decnumber_repo = "/Users/moshe/hercules-helper/extpkgs/repos/decNumber-0"
softfloat_repo = "/Users/moshe/hercules-helper/extpkgs/repos/SoftFloat-0"
telnet_repo    = "/Users/moshe/hercules-helper/extpkgs/repos/telnet-0"
install_dir    = "/Users/moshe/hercules-helper/extpkgs/."
cpu            = "x86"
crypto ...
  64-bit Debug ...
  FAILED!

One or more External Packages has FAILED!  :(
-----------------------------------------------------------------

Skipping step: autogen.sh (--no-autogen)
-----------------------------------------------------------------

Step: configure:

Regina REXX is present. Using configure option: --enable-regina-rexx
Disabling "getopt wrapper kludge" for Apple Darwin

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
~/hercules-helper/hyperion ~/hercules-helper/hyperion
CFLAGS=-frecord-gcc-switches ../configure --enable-optimization="-O2 -march=native" --enable-extpkgs=/Users/moshe/hercules-helper/extpkgs --prefix=/Users/moshe/hercules-helper/herc4x --enable-custom="Built using Hercules-Helper (version: v0.9.6-34-g286c960)" --enable-regina-rexx --disable-getoptwrapper

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../autoconf/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether make supports nested variables... (cached) no
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking target system type... x86_64-apple-darwin18.7.0
checking whether make supports the include directive... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/moshe/hercules-helper/hyperion/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
[[ error: ]] configure failed!

**Comment by wrljet** [comment]
Moshe,

From the error msg you received early on in the process, it appears the Xcode command line tools installation
may need to be refreshed.  There's a lot of chatter in the web about this getting goofed up during various updates.

I have updated the scripts to try to detect this situation.
I ask that you try them out _before_ applying the above fix, so we'll know if the error detection works.

Refresh/reclone the repo.
Then run your invocation again, but please add the `-p` option so it'll pause between steps, making it
easier to see errors.

```
 ./hyperion-buildall.sh --homebrew -v -p
```

Hopefully that will tell you it's recognized the condition.

Running:

```
./macOS-prerequisites.sh
```
should detect and automatically attempt the Xcode reinstallation.

If (and when) this doesn't automatically work, you can run that by-hand with:

```
xcode-select --install
```

Thanks,
Bill

**Comment by moshix** [comment]
yes, xcode-select --install solved the problem. thanks!
