### ISSUE TITLE
Hyperion-buildall script uses an outdated fork of SDL-Hercules

### ISSUE THREAD

**Issue by jeff-snyder** [wrljet/hercules-helper#18]
Hi Bill,

A few days ago, Fish committed a fix for a problem affecting SIE functionality in cpu.c that I wanted to test (commit e24c303, on 10/10).  On an Ubuntu system that did not have any Hercules installed, I downloaded the Hercules helper repository and ran hyperion-buildall.  Unfortunately, it is currently configured to use a wrljet fork of SDL-Hercules instead of the master SDL version, so I did not get that fix included.

I don't know if the issue you reference in the configuration file has been resolved yet, but I was able to work around this by pointing the script back to the main repository and build it.

hercules-helper.conf (as modified by me):

`...`
`# Temporarily set up to use my fork of SDL-Hercules `
`# while Fish et. al. straighten out gcc function inlining.`
`...`
`# Git repo for SDL-Hercules Hyperion`
`git_repo_hyperion=https://github.com/SDL-Hercules-390/hyperion.git`
`# git_repo_hyperion=https://github.com/wrljet/hyperion.git`
`...`

If the gcc issue has not been resolved, would it be possible to bring the fork back into sync with the master repository?  Or maybe just put out some kind of warning message about the temporary gcc workaround so users can choose whether or not to use the wrljet fork?  Your helper scripts are really convenient and I'd hate to see anybody else get bit by this.

**Comment by wrljet** [comment]
Builds with current SDL-Hercules repo are working well now, building and passing checks on many 
diverse systems.  And 4.4 is hoped to be released shortly.

The default clone repo in the Hercules-Helper config file has been pointed back to the official repo.

Bill
