### ISSUE TITLE
Pls add support of e2k architecture and Elbrus linux

### ISSUE THREAD

**Issue by trknz** [wrljet/hercules-helper#19]
System detection:
OS Type          : Linux
Machine Arch     : e2k
Memory Total (MB): 128736
Memory Free  (MB): 34206
VERSION_ID       : elbrus
VERSION_ID_LIKE  :
VERSION_PRETTY   : Elbrus Linux 6.0.1
VERSION_STR      : 6
Language         : LANG=ru_RU.UTF-8

Checking for Windows WSL2... nope
Checking for Windows WSL1... nope

[[ error: ]] Your system (Elbrus Linux 6.0.1) is not (yet) supported!

The Elbrus Linux is based on Debian

**Comment by wrljet** [comment]
I haven't forgotten you.

**Comment by wrljet** [comment]
Thanks to a very supportive member of our community I have been given access to an Elbrus e2k system,
and am actively working on it, with good progress on porting SDL-Hercules.

![4IfIKnO08wgLpBFW](https://user-images.githubusercontent.com/3638124/150875108-2bc0b9c4-061d-447b-9a3b-013c9b5e3414.png)

![DPxC7Z0MTE01fDbX](https://user-images.githubusercontent.com/3638124/150875116-44593c19-8611-4a63-897b-75cc38c523e1.png)

**Comment by wrljet** [comment]
Just got all the Hercules tests to run!

**Comment by wrljet** [comment]
This should now be usable as of commit https://github.com/wrljet/hercules-helper/commit/587cf2fe4bd41734e3e56c91ae6cb1bdce528db4, and SDL-Hercules commit https://github.com/SDL-Hercules-390/hyperion/commit/2e6df3669875421960105d34ce35d26a2bcf0e99 .

Note: the required packages handling for Elbrus e2k is not 100%. I did not have sudo access on
the system I was kindly given access to, on which I did this work, so I could not fully test with missing
packages.

The package names are *similar* to Debian:
```
build-essential cmake autoconf automake flex gawk m4 libtool libcap bzip2 zlib
```
