### ISSUE TITLE
Make check fails

### ISSUE THREAD

**Issue by geekofurl** [wrljet/hercules-helper#20]
After downloading a fresh copy of hercules-helper, I ran the recommended command:
    ~/hercules-helper/hyperion-buildall.sh --verbose --prompts
make check failed 1 test.  Attached is the build-commands-2021-11-01.log.

Rick

**Comment by geekofurl** [comment]
Forgot the attachment ;-{

#!/usr/bin/env bash

if [[ $TRACE == true ]]; then
    set -x # For debugging, show all commands as they are being run
fi

# Created by Hercules-Helper version: 
# /home/pi/hercules-helper/hyperion-buildall.sh/hyperion-buildall.sh: v0.9.6-58-gf56acfb

# Linux mvstk4 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

# C compiler: cc (Raspbian 8.3.0-6+rpi1) 8.3.0

# Environment variables used:
# PATH="/home/pi/tk4-/herc44/linux/arm/bin:/home/pi/tk4-/herc44/linux/armbin:/home/pi/bin:/home/pi/connect:/usr/local/bin:/usr/local/scripts:/usr/local/sbin:/etc:/usr/bin:/usr/sbin:/bin:/sbin:"
# CC="cc"
# CFLAGS=""
# CPPFLAGS=""
# LDFLAGS=""

opt_build_dir="/home/pi/hyperion"
opt_install_dir="/home/pi/herc4x"
opt_regina_dir="Regina-REXX-3.6"
opt_regina_tarfile="Regina-REXX-3.6.tar.gz"
opt_regina_url="http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz"
git_repo_hyperion="https://github.com/wrljet/hyperion.git"
git_branch_hyperion=""
git_commit_hyperion=""
git_repo_gists="https://github.com/SDL-Hercules-390/gists.git"
git_branch_gists=""
git_repo_extpkgs="https://github.com/SDL-Hercules-390"
git_branch_extpkgs=""

# Install required packages: 
sudo apt install git wget time ncat build-essential cmake autoconf automake flex gawk m4 libltdl-dev libcap2-bin libbz2-dev zlib1g-dev

# git clone required repos
cd $opt_build_dir
mkdir -p $opt_install_dir
rm -rf hyperion
git clone $git_repo_hyperion

cd $opt_build_dir
rm -rf extpkgs
mkdir extpkgs
cd extpkgs/
git clone $git_repo_gists

mkdir repos && cd repos
rm -rf *
git clone $git_repo_extpkgs/crypto crypto-0
git clone $git_repo_extpkgs/decNumber decNumber-0
git clone $git_repo_extpkgs/SoftFloat SoftFloat-0
git clone $git_repo_extpkgs/telnet telnet-0
cd $opt_build_dir/hyperion

# Check program versions
util/bldlvlck

# Prepare and build extpkgs
cd $opt_build_dir/extpkgs
cp gists/extpkgs.sh .
cp gists/extpkgs.sh.ini .
# Change 'x86' to 'aarch64' for 64-bit, or 'arm' for 32-bit, etc.
mv extpkgs.sh.ini extpkgs.sh.ini-orig
sed "s/x86/arm/" extpkgs.sh.ini-orig > extpkgs.sh.ini

cd $opt_build_dir/extpkgs
./extpkgs.sh  c d s t

cd $opt_build_dir/hyperion

# Do an out-of-source build
pushd $opt_build_dir/hyperion
mkdir -p build
cd build

# Configure and build Hercules
CFLAGS=-frecord-gcc-switches ../configure \
    --enable-optimization="-O2 -march=native" \
    --enable-extpkgs=$opt_build_dir/extpkgs \
    --prefix=$opt_install_dir \
    --enable-custom="Built using Hercules-Helper (version: v0.9.6-58-gf56acfb)" \
    --enable-regina-rexx \
     \
     \
    
popd >/dev/null;
cd build
make clean
time make -j 6 2>&1
time make check
===============================================================================
BASH LOG
===============================================================================
../tests/runtest  ../tests
Files: ../tests/1403.tst ../tests/3211.tst ../tests/agf.tst ../tests/awsbsf.tst ../tests/bfp-001-divtoint.tst ../tests/bfp-002-loadr.tst ../tests/bfp-003-loadfpi.tst ../tests/bfp-004-cvttolog.tst ../tests/bfp-005-cvttolog64.tst ../tests/bfp-006-cvttofix.tst ../tests/bfp-007-cvttofix64.tst ../tests/bfp-008-cvtfrlog.tst ../tests/bfp-009-cvtfrlog64.tst ../tests/bfp-010-cvtfrfix.tst ../tests/bfp-011-cvtfrfix64.tst ../tests/bfp-012-loadtest.tst ../tests/bfp-013-comps.tst ../tests/bfp-014-divide.tst ../tests/bfp-015-sqrt.tst ../tests/bfp-016-add.tst ../tests/bfp-017-loadl.tst ../tests/bfp-018-subtract.tst ../tests/bfp-019-multiply.tst ../tests/bfp-020-multlonger.tst ../tests/bfp-021-multadd.tst ../tests/bfp-022-multsub.tst ../tests/bim-001-add-sub.tst ../tests/CBUC.tst ../tests/CCW-ILS.tst ../tests/CDSG.tst ../tests/cipher.tst ../tests/CLCL-et-al.tst ../tests/CLCL.tst ../tests/cmd-abs.tst ../tests/cmd-rv.tst ../tests/CMPSC.tst ../tests/cr.tst ../tests/csxtr.tst ../tests/digest.tst ../tests/FAC53.tst ../tests/FAC5861.tst ../tests/fix-page.tst ../tests/hetbsf.tst ../tests/ifelse.tst ../tests/ilc.tst ../tests/invpsw.tst ../tests/kimd-hw.tst ../tests/klmd-hw.tst ../tests/kmac-hw.tst ../tests/kmc-hw.tst ../tests/kmctr-hw.tst ../tests/kmf-hw.tst ../tests/km-hw.tst ../tests/kmo-hw.tst ../tests/leapfrog.tst ../tests/logicimm.tst ../tests/mainsize.tst ../tests/mhi.tst ../tests/mvcle.tst ../tests/mvcos-001.tst ../tests/pfpo.tst ../tests/privop.tst ../tests/problem.tst ../tests/pr.tst ../tests/runtest0.tst ../tests/runtest4.tst ../tests/semipriv.tst ../tests/sigp.tst ../tests/ssk370.tst ../tests/sske370.tst ../tests/sske390.tst ../tests/sske.tst ../tests/stfl.tst ../tests/stidp-force.tst ../tests/stidp.tst ../tests/str-001-cksm.tst ../tests/str-001-clst.tst ../tests/str-001-mvst.tst ../tests/str-001-srst.tst ../tests/tape.tst ../tests/timeout.tst ../tests/wild.tst ../tests/zeos.tst
Variable $ptrsize            set to "4"
Variable $platform           set to "Linux"
Variable $can_s370_mode      set to "1"
Variable $can_esa390_mode    set to "1"
Variable $can_zarch_mode     set to "1"
Variable $max_cpu_engines    set to "64"
Variable $libraries          set to "Shared"
Variable $threading_model    set to "POSIX"
Variable $locking_model      set to "Error"
Variable $shared_devices     set to "1"
Variable $HDL                set to "1"
Variable $externalgui        set to "1"
Variable $IPV6               set to "1"
Variable $HTTP               set to "1"
Variable $sqrtl              set to "1"
Variable $sighandling        set to "1"
Variable $CCKD_BZIP2         set to "1"
Variable $HET_BZIP2          set to "1"
Variable $ZLIB               set to "1"
Variable $regex              set to "1"
Variable $rexx_supported     set to "0"
Variable $rexx_supported     set to "1"
Variable $HAO                set to "1"
Variable $NLS                set to "0"
Variable $cmpxchg1           set to "1"
Variable $cmpxchg4           set to "1"
Variable $cmpxchg8           set to "1"
Variable $hatomics           set to "atomicIntrinsics"
Variable $rexx_package       set to "Regina"
Variable $rexx_VERSION       set to "REXX-Regina_3.6(MT) 5.00 31 Dec 2011"
Variable $rexx_SOURCE        set to "UNIX"
Variable $rexx_Mode          set to "Command"
Variable $rexx_MsgLevel      set to "0"
Variable $rexx_MsgPrefix     set to "0"
Variable $rexx_ErrPrefix     set to "0"
Variable $rexx_Resolver      set to "1"
Variable $rexx_SysPath       set to "1"
Variable $rexx_RexxPath      set to ""
Variable $rexx_Extensions    set to ".REXX:.rexx:.REX:.rex:.CMD:.cmd:.RX:.rx"
Test "1403 printer Load UCS Buffer":  2 OK compares.  All pass.
Test "3211 printer (Regina)":  2 OK compares.  All pass.
Test "agf 20161211 12.44":  10 OK compares.  All pass.
Test "S/370 AWS tape BSF into Load Point":  5 OK compares.  All pass.
Test "bfp-001-divtoint.tst:   DIEBR, DIDBR":  1585 OK compares.  All pass.
Test "bfp-002-loadr.tst:      LEDBR, LEDB, LEXBR, LEXB, LDXBR, LDXB":  395 OK compares.  All pass.
Test "bfp-003-loadfpi.tst:    CFEBR, CFEBRA, CFDBR, CFDBRA, CFXBR, CFXBRA":  362 OK compares.  All pass.
Test "bfp-004-cvttolog.tst:   CLFEBR, CLFDBR, CLFXBR":  211 OK compares.  All pass.
Test "bfp-005-cvttolog64.tst: CLGEBR, CLGDBR, CLGXBR":  271 OK compares.  All pass.
Test "bfp-006-cvttofix.tst:   CFEBR, CFEBRA, CFDBR, CFDBRA, CFXBR, CFXBRA":  295 OK compares.  All pass.
Test "bfp-007-cvttofix64.tst: CGEBR, CGBRA, CGDBR, CGDBRA, CGXBR, CGXBRA":  387 OK compares.  All pass.
Test "bfp-008-cvtfrlog.tst:   CELFBR, CDLFBR, CXLFBR":  49 OK compares.  All pass.
Test "bfp-009-cvtfrlog64.tst: CELGBR, CDLGBR, CXLGBR":  73 OK compares.  All pass.
Test "bfp-010-cvtfrfix.tst:   CEFBR, CEFBRA, CDFBR, CDFBRA, CXFBR, CXFBRA":  56 OK compares.  All pass.
Test "bfp-011-cvtfrfix64.tst: CEGBR, CEGBRA, CDGBR, CDGBRA, CXGBR, CXGBRA":  119 OK compares.  All pass.
Test "bfp-012-loadtest.tst:   LTEBR, LTDBR, LTXBR, TCEB, TCDB, TCXB":  79 OK compares.  All pass.
Test "bfp-013-comps.tst:      CEBR, CEB, CDBR, CDB, CXBR, KEBR, KEB, KDBR, KDB, KXBR":  385 OK compares.  All pass.
Test "bfp-014-divide.tst:     DEBR, DEB, DDBR, DDB, DXBR":  645 OK compares.  All pass.
Test "bfp-015-sqrt.tst:       SQEBR, SQEB, SQDBR, SQDB, SQXBR":  131 OK compares.  All pass.
Test "bfp-016-add.tst:        AEBR, AEB, ADBR, ADB, AXBR":  1017 OK compares.  All pass.
Test "bfp-017-loadl.tst:      LDEBR, LDEB, LXEBR, LXEB, LXDBR, LXDB":  170 OK compares.  All pass.
Test "bfp-018-subtract.tst:   SEBR, SEB, SDBR, SDB, SXBR":  1017 OK compares.  All pass.
Test "bfp-019-multiply.tst:   MEEBR, MEEB, MDBR, MDB, MXBR":  729 OK compares.  All pass.
Test "bfp-020-multlonger.tst: MDEBR, MDEB, MXDBR, MXDB":  513 OK compares.  All pass.
Test "bfp-021-multadd.tst:    MAEBR, MAEB, MADBR, MADB":  2708 OK compares.  All pass.
Test "bfp-022-multsub.tst:    MSEBR, MSEB, MSDBR, MSDB":  2708 OK compares.  All pass.
Test "bim-001-add-sub.tst:   AR, AGR, SR and SGR":  181 OK compares.  All pass.
>>>>> line 60279: Received unexpected wait state:  0002000000000000 0000000000010BAD
>>>>> line 60280: Received unexpected wait state:  0002000000000000 0000000000010BAD
Test "CBUC (Concurrent Block Update Consistency)":  0 OK compares.  2 failures.
Test "CCW-ILS (CCW Incorrect Length Suppression)":  2 OK compares.  All pass.
Test "for CDSG, STPQ and LPQ Instructions":  3 OK compares.  All pass.
Test "cipher 20161202 12.03":  305 OK compares.  All pass.
Test "CLCL-et-al (Test CLCL, MVCIN and TRT instructions)":  2 OK compares.  All pass.
Test "CLCL Unaligned Buffers Test":  1 OK compares.  All pass.
Test "S/370-abs-0":  14 OK compares.  All pass.
Test "S/370-abs-1":  14 OK compares.  All pass.
Test "S/370-abs-pr":  14 OK compares.  All pass.
Test "S/370-abs-pr+1":  14 OK compares.  All pass.
Test "S/370-abs-0x1":  20 OK compares.  All pass.
Test "S/370-abs-1xpr":  20 OK compares.  All pass.
Test "S/370-abs-prx3":  20 OK compares.  All pass.
Test "S/390-abs-0":  14 OK compares.  All pass.
Test "S/390-abs-1":  14 OK compares.  All pass.
Test "S/390-abs-pr":  14 OK compares.  All pass.
Test "S/390-abs-pr+1":  14 OK compares.  All pass.
Test "S/390-abs-0x1":  20 OK compares.  All pass.
Test "S/390-abs-1xpr":  20 OK compares.  All pass.
Test "S/390-abs-prx3":  20 OK compares.  All pass.
Test "z/Arch-abs-0":  14 OK compares.  All pass.
Test "z/Arch-abs-1":  14 OK compares.  All pass.
Test "z/Arch-abs-pr":  14 OK compares.  All pass.
Test "z/Arch-abs-pr+1":  14 OK compares.  All pass.
Test "z/Arch-abs-0x1":  20 OK compares.  All pass.
Test "z/Arch-abs-1xpr":  20 OK compares.  All pass.
Test "z/Arch-abs-prx3":  20 OK compares.  All pass.
Test "S/370-r-0":  26 OK compares.  All pass.
Test "S/370-r-1":  26 OK compares.  All pass.
Test "S/370-r-2":  26 OK compares.  All pass.
Test "S/370-r-3":  26 OK compares.  All pass.
Test "S/370-r-pr4":  26 OK compares.  All pass.
Test "S/370-r-pr5":  26 OK compares.  All pass.
Test "S/370-r-6":  26 OK compares.  All pass.
Test "S/370-r-0x1":  38 OK compares.  All pass.
Test "S/370-r-1x2":  38 OK compares.  All pass.
Test "S/370-r-2x3":  38 OK compares.  All pass.
Test "S/370-r-3xpr4":  38 OK compares.  All pass.
Test "S/370-r-pr4xpr5":  38 OK compares.  All pass.
Test "S/370-r-pr5x6":  38 OK compares.  All pass.
Test "S/390-r-0":  14 OK compares.  All pass.
Test "S/390-r-1":  14 OK compares.  All pass.
Test "S/390-r-pr":  14 OK compares.  All pass.
Test "S/390-r-3":  14 OK compares.  All pass.
Test "S/390-r-0x1":  20 OK compares.  All pass.
Test "S/390-r-1xpr":  20 OK compares.  All pass.
Test "S/390-r-prx3":  20 OK compares.  All pass.
Test "z/Arch-r-0":  26 OK compares.  All pass.
Test "z/Arch-r-1":  26 OK compares.  All pass.
Test "z/Arch-r-2":  26 OK compares.  All pass.
Test "z/Arch-r-3":  26 OK compares.  All pass.
Test "z/Arch-r-pr4":  26 OK compares.  All pass.
Test "z/Arch-r-pr5":  26 OK compares.  All pass.
Test "z/Arch-r-6":  26 OK compares.  All pass.
Test "z/Arch-r-0x1":  26 OK compares.  All pass.
Test "z/Arch-r-1x2":  26 OK compares.  All pass.
Test "z/Arch-r-2x3":  26 OK compares.  All pass.
Test "z/Arch-r-3xpr4":  26 OK compares.  All pass.
Test "z/Arch-r-pr4xpr5":  26 OK compares.  All pass.
Test "z/Arch-r-pr5x6":  26 OK compares.  All pass.
Test "S/370-v-0":  26 OK compares.  All pass.
Test "S/370-v-1":  26 OK compares.  All pass.
Test "S/370-v-2":  26 OK compares.  All pass.
Test "S/370-v-3":  26 OK compares.  All pass.
Test "S/370-v-pr4":  26 OK compares.  All pass.
Test "S/370-v-pr5":  26 OK compares.  All pass.
Test "S/370-v-6":  26 OK compares.  All pass.
Test "S/370-v-0x1":  38 OK compares.  All pass.
Test "S/370-v-1x2":  38 OK compares.  All pass.
Test "S/370-v-2x3":  38 OK compares.  All pass.
Test "S/370-v-3xpr4":  38 OK compares.  All pass.
Test "S/370-v-pr4xpr5":  38 OK compares.  All pass.
Test "S/370-v-pr5x6":  38 OK compares.  All pass.
Test "S/390-v-0":  14 OK compares.  All pass.
Test "S/390-v-1":  14 OK compares.  All pass.
Test "S/390-v-pr":  14 OK compares.  All pass.
Test "S/390-v-3":  14 OK compares.  All pass.
Test "S/390-v-0x1":  20 OK compares.  All pass.
Test "S/390-v-1xpr":  20 OK compares.  All pass.
Test "S/390-v-prx3":  20 OK compares.  All pass.
Test "z/Arch-v-0":  26 OK compares.  All pass.
Test "z/Arch-v-1":  26 OK compares.  All pass.
Test "z/Arch-v-2":  26 OK compares.  All pass.
Test "z/Arch-v-3":  26 OK compares.  All pass.
Test "z/Arch-v-pr4":  26 OK compares.  All pass.
Test "z/Arch-v-pr5":  26 OK compares.  All pass.
Test "z/Arch-v-6":  26 OK compares.  All pass.
Test "z/Arch-v-0x1":  26 OK compares.  All pass.
Test "z/Arch-v-1x2":  26 OK compares.  All pass.
Test "z/Arch-v-2x3":  26 OK compares.  All pass.
Test "z/Arch-v-3xpr4":  26 OK compares.  All pass.
Test "z/Arch-v-pr4xpr5":  26 OK compares.  All pass.
Test "z/Arch-v-pr5x6":  26 OK compares.  All pass.
Test "CMPSC (Compression Call)":  2 OK compares.  All pass.
Test "Initial control register values":  9 OK compares.  All pass.
Test "csxtr csdtr cxstr cxutr 20160605 09.38":  8 OK compares.  All pass.
Test "digest 20161202 12.03":  57 OK compares.  All pass.
Test "Facility 53 Instructions":  1 OK compares.  All pass.
Test "FAC5861: Quick Test of Misc. Instr. Ext. 2 & 3":  1 OK compares.  All pass.
Test "fix-page.tst:":  5 OK compares.  All pass.
Test "S/370 HET (ZLIB) tape BSF into Load Point":  5 OK compares.  All pass.
Test "S/370 HET (BZIP2) tape BSF into Load Point":  5 OK compares.  All pass.
Test "IF-ELSE-01":  2 OK compares.  All pass.
Test "IF-ELSE-02":  2 OK compares.  All pass.
Test "IF-ELSE-03":  2 OK compares.  All pass.
Test "IF-ELSE-04":  2 OK compares.  All pass.
Test "IF-ELSE-05":  2 OK compares.  All pass.
Test "IF-ELSE-06":  2 OK compares.  All pass.
Test "IF-ELSE-07":  2 OK compares.  All pass.
Test "ilc":  3 OK compares.  All pass.
Test "invpsw processed 16 Jan 2016 12:11:11 by bldhtc.rexx":  1 OK compares.  All pass.
Test "KIMD fc0":  2 OK compares.  All pass.
Test "KIMD fc1":  3 OK compares.  All pass.
Test "KIMD fc2":  3 OK compares.  All pass.
Test "KIMD fc3":  5 OK compares.  All pass.
Test "KIMD fc65":  2 OK compares.  All pass.
Test "KLMD fc0":  2 OK compares.  All pass.
Test "KLMD fc1":  3 OK compares.  All pass.
Test "KLMD fc2":  3 OK compares.  All pass.
Test "KLMD fc3":  5 OK compares.  All pass.
Test "KMAC fc0":  2 OK compares.  All pass.
Test "KMAC fcbad":  2 OK compares.  All pass.
Test "KMAC fc1":  2 OK compares.  All pass.
Test "KMAC fc2":  2 OK compares.  All pass.
Test "KMAC fc3":  2 OK compares.  All pass.
Test "KMAC fc9":  2 OK compares.  All pass.
Test "KMAC fc10":  2 OK compares.  All pass.
Test "KMAC fc11":  2 OK compares.  All pass.
Test "KMAC fc18":  2 OK compares.  All pass.
Test "KMAC fc19":  2 OK compares.  All pass.
Test "KMAC fc20":  2 OK compares.  All pass.
Test "KMAC fc26":  2 OK compares.  All pass.
Test "KMAC fc27":  2 OK compares.  All pass.
Test "KMAC fc28":  2 OK compares.  All pass.
Test "KMC fc0":  2 OK compares.  All pass.
Test "KMC bad":  2 OK compares.  All pass.
Test "KMC badreg0":  2 OK compares.  All pass.
Test "KMC badreg3":  2 OK compares.  All pass.
Test "KMC fc1":  3 OK compares.  All pass.
Test "KMC fc2":  3 OK compares.  All pass.
Test "KMC fc3":  3 OK compares.  All pass.
Test "KMC fc9":  3 OK compares.  All pass.
Test "KMC fc10":  3 OK compares.  All pass.
Test "KMC fc11":  3 OK compares.  All pass.
Test "KMC fc18":  3 OK compares.  All pass.
Test "KMC fc19":  3 OK compares.  All pass.
Test "KMC fc20":  3 OK compares.  All pass.
Test "KMC fc26":  3 OK compares.  All pass.
Test "KMC fc27":  3 OK compares.  All pass.
Test "KMC fc28":  3 OK compares.  All pass.
Test "KMC fc67":  3 OK compares.  All pass.
Test "KMCTR fc0":  2 OK compares.  All pass.
Test "KMCTR bad":  2 OK compares.  All pass.
Test "KMCTR fc1":  3 OK compares.  All pass.
Test "KMCTR fc2":  3 OK compares.  All pass.
Test "KMCTR fc3":  3 OK compares.  All pass.
Test "KMCTR fc9":  3 OK compares.  All pass.
Test "KMCTR fc10":  3 OK compares.  All pass.
Test "KMCTR fc11":  3 OK compares.  All pass.
Test "KMCTR fc18":  2 OK compares.  All pass.
Test "KMCTR fc19":  2 OK compares.  All pass.
Test "KMCTR fc20":  2 OK compares.  All pass.
Test "KMCTR fc26":  3 OK compares.  All pass.
Test "KMCTR fc27":  3 OK compares.  All pass.
Test "KMCTR fc28":  3 OK compares.  All pass.
Test "KMF fc0":  2 OK compares.  All pass.
Test "KMF bad":  2 OK compares.  All pass.
Test "KMF fc1":  3 OK compares.  All pass.
Test "KMF fc2":  3 OK compares.  All pass.
Test "KMF fc3":  3 OK compares.  All pass.
Test "KMF fc9":  3 OK compares.  All pass.
Test "KMF fc10":  3 OK compares.  All pass.
Test "KMF fc11":  3 OK compares.  All pass.
Test "KMF fc18":  3 OK compares.  All pass.
Test "KMF fc19":  3 OK compares.  All pass.
Test "KMF fc20":  3 OK compares.  All pass.
Test "KMF fc26":  3 OK compares.  All pass.
Test "KMF fc27":  3 OK compares.  All pass.
Test "KMF fc28":  3 OK compares.  All pass.
Test "KM fc0":  2 OK compares.  All pass.
Test "KM fc1":  3 OK compares.  All pass.
Test "KM fc2":  3 OK compares.  All pass.
Test "KM fc3":  3 OK compares.  All pass.
Test "KM fc9":  3 OK compares.  All pass.
Test "KM fc10":  3 OK compares.  All pass.
Test "KM fc11":  3 OK compares.  All pass.
Test "KM fc18":  3 OK compares.  All pass.
Test "KM fc19":  3 OK compares.  All pass.
Test "KM fc20":  3 OK compares.  All pass.
Test "KM fc26":  3 OK compares.  All pass.
Test "KM fc27":  3 OK compares.  All pass.
Test "KM fc28":  3 OK compares.  All pass.
Test "KM fc50":  3 OK compares.  All pass.
Test "KM fc52":  3 OK compares.  All pass.
Test "KM fc58":  3 OK compares.  All pass.
Test "KM fc60":  3 OK compares.  All pass.
Test "KMO fc0":  2 OK compares.  All pass.
Test "KMO bad":  2 OK compares.  All pass.
Test "KMO fc1":  3 OK compares.  All pass.
Test "KMO fc2":  3 OK compares.  All pass.
Test "KMO fc3":  3 OK compares.  All pass.
Test "KMO fc9":  3 OK compares.  All pass.
Test "KMO fc10":  3 OK compares.  All pass.
Test "KMO fc11":  3 OK compares.  All pass.
Test "KMO fc18":  3 OK compares.  All pass.
Test "KMO fc19":  3 OK compares.  All pass.
Test "KMO fc20":  3 OK compares.  All pass.
Test "KMO fc26":  3 OK compares.  All pass.
Test "KMO fc27":  3 OK compares.  All pass.
Test "KMO fc28":  3 OK compares.  All pass.
Test "leapfrog processed 16 Jan 2016 12:11:11 by bldhtc.rexx":  3 OK compares.  All pass.
Test "logicImmediate processed 12 Nov 2015 12:36:58 by bldhtc.rexx":  17 OK compares.  All pass.
Test "mainsize check storage size":  27 OK compares.  All pass.
Test "mhi":  4 OK compares.  All pass.
Test "mvcle-370":  3 OK compares.  All pass.
Test "mvcos-001.tst:":  1 OK compares.  All pass.
Test "PFPO-390: Perform Floating Point Operation (ESA/390 mode)":  1 OK compares.  All pass.
Test "PFPO-Z: Perform Floating Point Operation (z/Arch mode)":  1 OK compares.  All pass.
Test "privopisk":  2 OK compares.  All pass.
Test "privopiske":  2 OK compares.  All pass.
Test "privopgo":  3 OK compares.  All pass.
Test "problem":  2 OK compares.  All pass.
Test "z/Arch prefix register and real/absolute storage set/display":  10 OK compares.  All pass.
Test "ESA/390 prefix register and real/absolute storage set/display":  10 OK compares.  All pass.
Test "S/370 prefix register and real/absolute storage set/display":  10 OK compares.  All pass.
Test "runtest0: all cpus 0 seconds":  5 OK compares.  All pass.
Test "runtest4: all cpus 1-4 seconds":  5 OK compares.  All pass.
Test "semipriv":  5 OK compares.  All pass.
Test "sigp":  1 OK compares.  All pass.
Test "SSK S/370  Specification Exception (low reg bits)":  2 OK compares.  All pass.
Test "SSK S/370  Addressing Exception":  2 OK compares.  All pass.
Test "SSK S/370  page0":  8 OK compares.  All pass.
Test "SSK S/370  page1":  8 OK compares.  All pass.
Test "SSK S/370  page2":  8 OK compares.  All pass.
Test "SSK S/370  page3":  8 OK compares.  All pass.
Test "SSK S/370  page4":  8 OK compares.  All pass.
Test "SSK S/370  page5":  8 OK compares.  All pass.
Test "SSK S/370  page6":  8 OK compares.  All pass.
Test "SSK S/370  nextlast":  3 OK compares.  All pass.
Test "SSK S/370  lastpage":  3 OK compares.  All pass.
Test "SSKE S/370 Successful (low reg bits)":  2 OK compares.  All pass.
Test "SSKE S/370 Successful (high reg bit)":  2 OK compares.  All pass.
Test "SSKE S/370 Addressing Exception":  2 OK compares.  All pass.
Test "SSKE S/370 page0":  8 OK compares.  All pass.
Test "SSKE S/370 page1":  8 OK compares.  All pass.
Test "SSKE S/370 page2":  8 OK compares.  All pass.
Test "SSKE S/370 page3":  8 OK compares.  All pass.
Test "SSKE S/370 page4":  8 OK compares.  All pass.
Test "SSKE S/370 page5":  8 OK compares.  All pass.
Test "SSKE S/370 nextlast":  3 OK compares.  All pass.
Test "SSKE S/370 lastpage":  3 OK compares.  All pass.
Test "SSKE S/390 Successful (low reg bits)":  2 OK compares.  All pass.
Test "SSKE S/390 Successful (high reg bit)":  2 OK compares.  All pass.
Test "SSKE S/390 Addressing Exception":  2 OK compares.  All pass.
Test "SSKE S/390 page0":  8 OK compares.  All pass.
Test "SSKE S/390 page1":  8 OK compares.  All pass.
Test "SSKE S/390 page2":  8 OK compares.  All pass.
Test "SSKE S/390 page3":  8 OK compares.  All pass.
Test "SSKE S/390 page4":  8 OK compares.  All pass.
Test "SSKE S/390 page5":  8 OK compares.  All pass.
Test "SSKE S/390 page6":  8 OK compares.  All pass.
Test "SSKE S/390 nextlast":  3 OK compares.  All pass.
Test "SSKE S/390 lastpage":  3 OK compares.  All pass.
Test "sske#1":  2 OK compares.  All pass.
Test "sske#2":  53 OK compares.  All pass.
Test "STFL and STFLE":  12 OK compares.  All pass.
Test "cpuverid FORCE (z/Arch LPAR FMT-0)":  2 OK compares.  All pass.
Test "S/370  BASIC  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "S/370  BASIC  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "S/370  LPAR  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "S/370  LPAR  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "S/370  BASIC  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "S/370  BASIC  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "S/370  LPAR  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "S/370  LPAR  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "ESA/390  BASIC  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "ESA/390  BASIC  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "ESA/390  LPAR  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "ESA/390  LPAR  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "ESA/390  BASIC  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "ESA/390  BASIC  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "ESA/390  LPAR  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "ESA/390  LPAR  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "z/Arch  BASIC  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "z/Arch  BASIC  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "z/Arch  LPAR  FMT-0  CPUs = 1":  2 OK compares.  All pass.
Test "z/Arch  LPAR  FMT-1  CPUs = 1":  2 OK compares.  All pass.
Test "z/Arch  BASIC  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "z/Arch  BASIC  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "z/Arch  LPAR  FMT-0  CPUs = 2":  2 OK compares.  All pass.
Test "z/Arch  LPAR  FMT-1  CPUs = 2":  2 OK compares.  All pass.
Test "str-001-cksm.tst:":  10 OK compares.  All pass.
Test "str-001-clst.tst:":  14 OK compares.  All pass.
Test "str-001-mvst.tst:":  11 OK compares.  All pass.
Test "str-001-srst.tst:":  10 OK compares.  All pass.
Test "Tape Data Chaining":  2 OK compares.  All pass.
Test "timeout":  1 OK compares.  All pass.
Test "multix":  2 OK compares.  All pass.
Test "multix1":  2 OK compares.  All pass.
Test "zeos":  6 OK compares.  All pass.
Did 327 tests.  1 failed; 326 OK.
make: *** [Makefile:3474: check] Error 1

real	0m44.323s
user	0m26.001s
sys	0m17.192s
-----------------------------------------------------------------

Step: install [without sudo]:  Hit return to continue^C

**Comment by wrljet** [comment]
CBUC (Concurrent Block Update Consistency) test is a known failure on the 32-bit Pi.
