### ISSUE TITLE
Hercules make fails on raspberry pi 3 using hercules-helper

### ISSUE THREAD

**Issue by rgschmi** [wrljet/hercules-helper#21]
All seems well until the make fails.  I have attached the log of the build process.  I'm using openSUSE linux.

[hyperion-buildall-2021-12-04.zip](https://github.com/wrljet/hercules-helper/files/7654882/hyperion-buildall-2021-12-04.zip)
s.

**Comment by wrljet** [comment]
Bob,

That is a combination of Pi and OS I have not tried before.  (or even was aware of)
I will get it fixed for you.

Bill

**Comment by rgschmi** [comment]
Hopefully that combination of pi and OS works.  I use the pi as a shared disk server and my old Hercules (3.11?) doesn't support DASD over 4gb.  I'm also trying to update my openSUSE, and I'm trying to find an image that fits in 1 gig.  May be time for  Pi 4! 

 I'll run the server on Windows for now.

I really like hercules-helper.  Makes it easy to install Hercules for a linux-challenged person like me!

**Comment by wrljet** [comment]
Yes, it's going to work.  I know what is wrong, simple fix.
  
I got a newer openSUSE booted and working on a Pi 3 B+.  But so far can't get your 42.2 version to boot.
Perhaps it only works on a non-B+.  ... developing ...

**Comment by rgschmi** [comment]
What openSUSE image did you use?  I'm open to upgrading it. I have a B (no +).

**Comment by wrljet** [comment]
Bob,

I used openSUSE 15.2.  I could not convince 42.2 or 42.3 to boot on a 3B or 3B+.

I wanted to use the same version you had, because you've got gcc 4.8.5, which is pretty old
(and the source of the error msg, as it doesn't support -march=native)

So I was not able to do a thorough test of my changes, but I think they will work.

Here's what I changed:

- Test the C compiler to see if '-march=native' works trying to use it.
  (this fixes the error you encountered)
- Add '--force-pi' option, for Raspberry Pi OSes that hide the CPU ID.
- Add detection of Raspberry Pi with openSUSE.
  (this lets my code that patches Regina sources for the Pi to run)
- Add 'time' package to auto installation for openSUSE.
  (the script uses 'time' which was missing from my fresh install)
- Skip 'mainsize' test on low memory openSUSE (Pi 3B).
  (FreeBSD and openSUSE don't behave well in low memory situations and cause the 'mainsize' test to fail)

Please give it a try and let me know what happens.

Bill

**Comment by rgschmi** [comment]
So close!   I still get a make failure and for some reason I did not get a log file and I don't know how to copy an xterm screen.  I can say the error is: Makefile:2120 recipe for target 'libhercu.la' failed

I can run it again with putty and copy the screen, but I'm curious why I didn't get a log.   My options were --prompt --verbose --no-rexx

**Comment by wrljet** [comment]
Bob,

I've *never* seen the log not get created. 
Perhaps there was some other bash error up higher that caused that?

Please do whatever you can to grab the output. :-)

You know what would be very helpful, if you could "zip" up you SD card image and upload it to the web someplace for me.
Like Google or Amazon drive.  Split into chunks no bigger than 2GB.

Bill

**Comment by wrljet** [comment]
You can get a screenshot of your host xterm window.

**Comment by rgschmi** [comment]
I feel kinda dumb.  I found the log files, in a different directory than the others.  I must have done something different.  Log attached.  

I can try to 'zip' the SD card, but I'll have to figure out how to split it up.  Worst case is I can let you FTP it from me.
[hyperion-buildall-2021-12-06-1.zip](https://github.com/wrljet/hercules-helper/files/7664281/hyperion-buildall-2021-12-06-1.zip)

**Comment by rgschmi** [comment]
It looks like line 308 indicates I have a down level libtool.  I'll check it out.

**Comment by wrljet** [comment]
What host OS are you using?  On Windows, WinRAR can create a .RAR file and break it into 2GB chunks.

I wouldn't worry about that libtool version.

Let me review the log first before you change anything.
(dinner and sleeping-in-front-of-the TV-with-the wife hour here)

Bill

**Comment by rgschmi** [comment]
Getting about that time for me, too!  I'm normally on Windows.  I'll check winRAR out.

Meanwhile, I'm going to try to find an openSUSE build that will fit on my pi.  Might have to go to JEOS.  I've tried KDE and XFCE builds to no avail.  I at least got a logon screen with XFCE, but then it hung.

**Comment by rgschmi** [comment]
I have an openSUSE 15.2 X11 desktop installed.  After the obligatory TV session, I will see if hercules-helper works!

**Comment by rgschmi** [comment]
Bill,

I have a good Hercules build on openSUSE 15.2.!  However, I can't seem to run it.  I keep getting a typo when I key in hercules.  Do I need to do something more?  Any special directory I need to be in? I got a cc=0 on the build.

**Comment by wrljet** [comment]
Excellent news!
Let me review that last log first, and I'll get back to you on the SD card image.

Bill

**Comment by wrljet** [comment]
Bob,

Before you edited your comment above, you originally wrote: "I have a good Hercules build on openSUSE 15.2.! However, I can't seem to run it. I keep getting a typo when I key in hercules."

What did you mean by "typo" and how did you fix it?

Bill

**Comment by wrljet** [comment]
Bob,

> I'd be happy to send you copy of the failing SD card.

Would you email me to discuss that outside of GitHub?
My email address is at the top of the hyperion-buildall.sh script.

Thanks,
Bill

**Comment by wrljet** [comment]
After working with Bob privately, this has been resolved for OpenSUSE 42 on Raspberry Pi 3B as well as newer OpeenSUSE versions.
