### ISSUE TITLE
Support for Mageia v8 

### ISSUE THREAD

**Issue by vbcoen** [wrljet/hercules-helper#22]
Please add suport for Mageia v8 (x64) to your script/s.

Mageia is a Redhat variant.

Tried to read the build script looking at centos but I do not understand the diffs as cannot tell what is used to check for and download/install from distros the extra needed libs etc.

**Comment by wrljet** [comment]
I will look into it for you.

Bill

**Comment by wrljet** [comment]
Vincent,

I've added support for Mageia v8.  (which I have never heard of before today)

I installed it on VMware.  It seems quite snappy in performance.

![Mageia-v8-system-info](https://user-images.githubusercontent.com/3638124/146693153-0c26f628-c7bd-4bc5-8f9f-3dde00528f1e.jpg)

During that process I selected these checkboxes:

![Mageia-v8-user-setup](https://user-images.githubusercontent.com/3638124/146693068-691a193c-caa6-408d-96b6-1bda8359e316.jpg)

Then out of the box, `git` and `sudo` were missing.  So I installed those using "Software Management", which
was called "Install & Remove Software" off the "Start" button menu.

From there, with the changes I've added to Hercules-Helper, it seemed to work well.

![Mageia-v8-hercules](https://user-images.githubusercontent.com/3638124/146693162-a9b54f3e-3134-406a-82bb-59db446634de.jpg)

Let me know if anything doesn't work.

Bill

**Comment by vbcoen** [comment]
Will do - have you committed the changes to git ?

**Comment by wrljet** [comment]
Yes

**Comment by wrljet** [comment]
Are you happy with it?  Can we close this issue?
