### ISSUE TITLE
Darwin level 21 warning on macOS Monterey 12.1 ARM64

### ISSUE THREAD

**Issue by rvjansen** [wrljet/hercules-helper#23]
During brew processing (brew is already there so of no real consequence) hercules-helper warns that it sees Darwin 21 where it expected to see Darwin 20. Build went OK so not real issue, for information only.

**Comment by wrljet** [comment]
Thank you for that report, René.

I will fix it and let you know.

I'm afraid I haven't updated my Mac Mini M1 to the Monterey yet.  But I'm sure I can reproduce it on one of my VMs.

Bill

**Comment by wrljet** [comment]
Oh, can you paste in what messages you got.

Thanks, Bill

**Comment by wrljet** [comment]
Fixed with commit https://github.com/wrljet/hercules-helper/commit/c9a63556f1b630a962c88b8352421ecb0ea0538c

**Comment by rvjansen** [comment]
thx!
