### ISSUE TITLE
On macOS Monterey 12.1 X86_64, configure.ac check for macro argument counting failed

### ISSUE THREAD

**Issue by rvjansen** [wrljet/hercules-helper#24]
```
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for off_t... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
configure: Using External Packages override directory /Users/rvjansen/apps/hercules-helper/herctest/extpkgs 
configure: NOTICE: sizeof(__int128_t) >= 16; max CPU engines = 128 
checking whether getopt wrapper kludge is necessary... no (forced)
ERROR: macro argument counting broken and cannot use -traditional-cpp option to work around it 
configure: error: Please correct the above error(s) and try again 
[1;31m[[ error: ]] [0mconfigure failed!
```
I had to hash out this test before compile would start, to no obvious detrimental effect. This step does not fail on the ARM64 machine. Both have the same Clang 13.

**Comment by wrljet** [comment]
There's just no end of trouble. :-)

I wonder why I didn't get that the other day when I was working on that system.

I will look into it.

Bill

**Comment by wrljet** [comment]
BTW, Clang 13 did not produce a working Hercules for me on Monterey 12.1 x86_64 (in VMware).
Neither did Clang 12.
I had to go back to Clang 11 to get one that worked.

**Comment by wrljet** [comment]
I'm glad I haven't let Apple update my Mac M1 to Monterey! :-)

**Comment by rvjansen** [comment]
Both of my Macs work fine now with Monterey and Clang 13.0.0 (Apple clang version 13.0.0 (clang-1300.0.29.30). As the test in config.ac is there at least since spinhawk, I dared to disable it, I am just curious which combination of releases leads to the failed test. So all is well for the moment.

**Comment by wrljet** [comment]
Could you zip up and send the buildall log that Hercules Helper produced?

**Comment by rvjansen** [comment]
[helperlog.zip](https://github.com/wrljet/hercules-helper/files/7781967/helperlog.zip)
Here it is.

**Comment by wrljet** [comment]
René,

Could you please run these two commands and paste the output in here:

```
brew --cellar libtool
find $(brew --cellar libtool) -type d -name "lib"
```

And I'm curious, you have these two environment variables set:
```
CPPFLAGS         : -I/usr/local/opt/gettext/include
LDFLAGS          : -L/usr/local/opt/gettext/lib
```

May I ask what those are for?

Bill

**Comment by rvjansen** [comment]
➜  ~ brew --cellar libtool
/usr/local/Cellar/libtool
➜  ~ find $(brew --cellar libtool) -type d -name "lib"
/usr/local/Cellar/libtool/2.4.6_4/lib

Those flags are for ... something else. I probably needed gettext for something or the other. This is a 2017 laptop that never was really cleaned and has hundreds of things built. The .zshrc where it is from might even be much older. It might have been cmake, swipl, hercules, oorexx, crexx, brexx, regina, something or the other. Does it form a problem? I have removed them if we need further experimentation.

René.

**Comment by wrljet** [comment]
> ... Does it form a problem? I have removed them if we need further experimentation.

No, I was just curious.

**Comment by wrljet** [comment]
In your build directory (probably `~/apps/hercules-helper/herctest/hyperion/build`) you should find `config.log`
Could you zip that and post it.

**Comment by rvjansen** [comment]
[configlog.zip](https://github.com/wrljet/hercules-helper/files/7796745/configlog.zip)
Hope that did not document all those boneheaded attempts before it worked

**Comment by wrljet** [comment]
I was looking for the original one, where you got the error msg:
`macro argument counting broken and cannot use -traditional-cpp option to work around it`

Ignore that for now.

Do you have `CC` or `GCC` environment variables set?

Do you have gcc installed somewhere on the system (in addition to Clang)?

**Comment by rvjansen** [comment]
There are no CC or GCC environment variable set. There are several copies of gcc (for Arduino etc) but not on the PATH.
Here is the original error config.log:
[configlog.zip](https://github.com/wrljet/hercules-helper/files/7797820/configlog.zip)

I wonder if this check - from the hyperion codebase .configure - makes any sense, seen the effect that when it is hashed out, everything still works. Because even if something in the toolchain is wrong, that toolchain builds a working hyperion.

**Comment by wrljet** [comment]
René, I'm trying to track down why that old test in `configure` is getting triggered on your system.
It is not on mine. And having spent the last year working on the autoconf stuff on *many* different
combinations of OS and compilers, I've never seen that error before.

I want to figure that out before I start changing configure on the SDL repo.

Also, have you run `make check`?  I ask because Clang 13 (and 12) do *not* build working Hercules for me.
They fail in the tests.

Bill

**Comment by rvjansen** [comment]
Bill,
I just re-ran the tests (could not remember very well, as it was last week) in make check and they run without error. I have two working hercules systems on Monterey with Clang 13 now. No odd things on VM and/or OS. I think the only special thing here is that I do not want Rexx support on these systems that have many versions of Rexx running and built from source.
As I know exactly what to do now, and this only happens on the X86_64, I would understand if you would drop this for the moment, maybe until it rears its head on another system.

**Comment by wrljet** [comment]
Since it doesn't pass the checks for me here (and I know of one other person having trouble), I can't drop it.
In fact I need to create an issue on SDL Hercules for this.  `:(`  But I'm waiting to do that until I know more
precisely what is going on.  (at the moment I believe it is related to function inlining)

Reviewing the `config.log` you sent from the original failing situation, I now see that the compiler
(which is called `gcc` in this case) is getting includes files (`stdio.h` in particular) from a directory
that isn't on my system.   `/usr/local/include`

And the compiler's reaction to that `stdio.h` results in the error msg from `configure` being triggered.
So at least that much is explained.

Could you run these two commands and tell me what it displays:

```
gcc -v
clang -v
```

Thanks, Bill

**Comment by rvjansen** [comment]
```
➜  ~ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
➜  ~ clang -v
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by rvjansen** [comment]
Some more tourist info: I think ```/usr/local/include``` is something that is added by homebrew, as it contains aliases to objects that belong to the Xcode command line package and to include files from homebrew installed packages.
Other note: my homebrew install existed before the hercules-helper install, but it is a fairly recent one. Since somewhere in 2020 I had a problem with homebrew in that some packages did not work and all was installed from source instead of with the binaries. Last december I found the root cause of this: homebrew lets you configure it to install to a bespoke path; but you'd better not, as lots of its recipes assume default path, and then build all from source, in the case of openssl and gcc, again and again. Since my reinstall with default paths everything is fine, and I did not consciously install gcc yet.
As verified below:
```
➜  ~ brew list
==> Formulae
autoconf	gettext		icu4c		libffi		lz4		openssl@1.1	unbound
automake	git-lfs		jansson		libidn2		m4		p11-kit		utf8proc
bdw-gc		gmp		krb5		libnghttp2	ncurses		pkg-config	wget
ca-certificates	gnu-sed		libarchive	libtasn1	nettle		postgresql	xz
cmake		gnutls		libb2		libtool		ninja		readline	zstd
emacs		guile		libevent	libunistring	nmap		tmux
➜  ~ brew list cask
Error: No such keg: /usr/local/Cellar/cask
```

**Comment by rvjansen** [comment]
And a sample from this directory, ```/usr/local/include```:
```
lrwxr-xr-x    1 rvjansen  staff     71 Feb  2  2020 spawn.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/spawn.h
lrwxr-xr-x    1 rvjansen  staff     47 Dec  7 19:48 sql3types.h@ -> ../Cellar/postgresql/14.1_1/include/sql3types.h
lrwxr-xr-x    1 rvjansen  staff     43 Dec  7 19:48 sqlca.h@ -> ../Cellar/postgresql/14.1_1/include/sqlca.h
lrwxr-xr-x    1 rvjansen  staff     50 Dec  7 19:48 sqlda-compat.h@ -> ../Cellar/postgresql/14.1_1/include/sqlda-compat.h
lrwxr-xr-x    1 rvjansen  staff     50 Dec  7 19:48 sqlda-native.h@ -> ../Cellar/postgresql/14.1_1/include/sqlda-native.h
lrwxr-xr-x    1 rvjansen  staff     43 Dec  7 19:48 sqlda.h@ -> ../Cellar/postgresql/14.1_1/include/sqlda.h
lrwxr-xr-x    1 rvjansen  staff     73 Feb  2  2020 sqlite3.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sqlite3.h
lrwxr-xr-x    1 rvjansen  staff     76 Feb  2  2020 sqlite3ext.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sqlite3ext.h
lrwxr-xr-x    1 rvjansen  staff     70 Feb  2  2020 stab.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stab.h
lrwxr-xr-x    1 rvjansen  staff     75 Feb  2  2020 standards.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/standards.h
lrwxr-xr-x    1 rvjansen  staff     72 Feb  2  2020 stddef.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stddef.h
lrwxr-xr-x    1 rvjansen  staff     72 Feb  2  2020 stdint.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h
lrwxr-xr-x    1 rvjansen  staff     71 Feb  2  2020 stdio.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h
lrwxr-xr-x    1 rvjansen  staff     72 Feb  2  2020 stdlib.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h
lrwxr-xr-x    1 rvjansen  staff     73 Feb  2  2020 strhash.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/strhash.h
lrwxr-xr-x    1 rvjansen  staff     72 Feb  2  2020 string.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h
lrwxr-xr-x    1 rvjansen  staff     76 Feb  2  2020 stringlist.h@ -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stringlist.h
```

**Comment by wrljet** [comment]
More recent testing (FEB 2022) with up-to-date Xcode and Clang13  on MacOS generates non-working (`make check` tests don't pass) Hercules.  Which is a SDL-Hercules issue (which I am pursuing) rather than Hercules-Helper build issue.

So I am closing this issue.
