### ISSUE TITLE
Fails to build hercules on s390x SLES (SUSE Linux Enterprise)

### ISSUE THREAD

**Issue by nix234** [wrljet/hercules-helper#25]
First thank you very much for that great tool!

So there are actually two problems:

1. The script fails to detect "sles" however it's easy i just changed the OS detection from Opensuse to sles.

2. It build's everything fine until i try's to link libhercs.la:

  CC       cardpch.lo
  CCLD     libhercs.la
/usr/lib64/gcc/s390x-suse-linux/7/../../../../s390x-suse-linux/bin/ld: cannot find -lcrypto32
/usr/lib64/gcc/s390x-suse-linux/7/../../../../s390x-suse-linux/bin/ld: cannot find -ldecNumber32
/usr/lib64/gcc/s390x-suse-linux/7/../../../../s390x-suse-linux/bin/ld: cannot find -lSoftFloat32
/usr/lib64/gcc/s390x-suse-linux/7/../../../../s390x-suse-linux/bin/ld: cannot find -ltelnet32
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2112: libhercs.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/linux1/bin/hercules-helper-0.9.8/hyperion/build'
make[1]: *** [Makefile:2529: all-recursive] Error 1
make[1]: Leaving directory '/home/linux1/bin/hercules-helper-0.9.8/hyperion/build'
make: *** [Makefile:1865: all] Error 2

real	1m46.316s
user	2m28.512s
sys	0m48.113s
[[ error: ]] Make failed!
finish() called, exit status = 1
linux1@test:~/bin/hercules-helper-0.9.8

Herc-helper: v0.9.8
OS: SLES15SP3
HW: LinuxONE

You can get a instance (Ubuntu,RHEL and SLES are available) for free (i think for 2 month, probably with reactivation later?) if you want to test it on your own on a real s390 mainframe here you go:
https://linuxone.cloud.marist.edu/#/register?flag=VM

And again, thanks for that great time-saver ;)

**Comment by nix234** [comment]
I already spun-up a ubuntu20.04 but the error is the same (build-log as attachment)
[build-log.txt](https://github.com/wrljet/hercules-helper/files/8216202/build-log.txt)

**Comment by wrljet** [comment]
I believe I have found the problem.  (on paper -- haven't tried it on an s390x system yet)

**Comment by nix234** [comment]
Hy Bill,

I'm all ears, how can i help? Do you want to give me the diff so i can test it, or can i provide you access to the machine?

**Comment by wrljet** [comment]
OK, it's been tested with:
Windows 10 host -> VMware -> Debian 10 -> Hercules -> Ubuntu s390x

Fix has been committed to:  https://github.com/SDL-Hercules-390/hyperion/commit/673efabbed9f3ea683e7738356b3a68a7dea5c3a

Update your Hercules-Helper to the latest from my repo.  This addresses the SLES issue.
(that detection was built but got lost somehow thanks to the power of git)

Edit your `hercules-helper.conf` and uncomment the line:

`git_branch_hyperion=develop`

Then run your `hyperion-buildall.sh` command.

Let me know what happens.
Bill

![image](https://user-images.githubusercontent.com/3638124/157770749-88261ba3-a4b9-40bf-b86c-b6c686d02178.png)

**Comment by wrljet** [comment]
They gave me an account on IBM LinuxONE Community Cloud today.  But I haven't tried it yet.

**Comment by nix234** [comment]
It builds and runs perfectly! 

`HHC00100I Thread id 000003ff970f2fd0, prio 5, name 'impl_thread' started
HHC00100I Thread id 000003ff95efe900, prio 4, name 'logger_thread' started
HHC01413I Hercules version 4.5.0.10705-SDL-DEV-g673efabb
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I Built using Hercules-Helper (version: v0.9.8-5-gc2450a8-dirty)
HHC01415I Build date: Mar 11 2022 at 04:51:59
HHC01417I Built with: GCC 7.5.0
HHC01417I Build type: GNU/Linux s390x host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 128
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I Without CCKD BZIP2 support
HHC01417I Without HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I With    Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    "Optimized" instructions
HHC01417I With    OPTION_USE_SKAIP_AS_LOCK
HHC01417I With    OPTION_SIE2BK_FLD_COPY
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 hatomics=C11
HHC01417I Running on: suse (Linux-5.3.18-150300.59.54-default s390x) MP=2
HHC01417I Built with crypto external package version 1.0.0.52-ga5096e5
HHC01417I Built with decNumber external package version 3.68.0.102-g3aa2f45
HHC01417I Built with SoftFloat external package version 3.5.0.105-g4b0c326
HHC01417I Built with telnet external package version 1.0.0.62-ge0e2a91
HHC00018W Hercules is NOT running in elevated mode
HHC00007I Previous message from function 'impl' at impl.c(1072)
HHC00150I Crypto module loaded (C) Copyright 2003-2016 by Bernard van der Helm
HHC00151I Activated facility: Message Security Assist
HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4
HHC17528I REXX(Regina) VERSION: REXX-Regina_3.6(MT) 5.00 31 Dec 2011
HHC17529I REXX(Regina) SOURCE:  UNIX
HHC17525I REXX(Regina) Rexx has been started/enabled
HHC17500I REXX(Regina) Mode            : Command
HHC17500I REXX(Regina) MsgLevel        : Off
HHC17500I REXX(Regina) MsgPrefix       : Off
HHC17500I REXX(Regina) ErrPrefix       : Off
HHC17500I REXX(Regina) Resolver        : On
HHC17500I REXX(Regina) SysPath    ( 4) : On
HHC17500I REXX(Regina) RexxPath   ( 0) :
HHC17500I REXX(Regina) Extensions ( 8) : .REXX:.rexx:.REX:.rex:.CMD:.cmd:.RX:.rx
HHC00111I Thread CPU Time IS available (_POSIX_THREAD_CPUTIME=0)
HHC00100I Thread id 000003ff9567a900, prio 7, name 'timer_thread' started
HHC00100I Thread id 000003ff9577b900, prio 2, name 'Processor CP00' started
HHC00811I Processor CP00: architecture mode z/Arch
HHC01432S Config file[1] : error in function fopen(): No such file or directory
HHC00007I Previous message from function 'process_config' at script.c(217)
HHC01420I Begin Hercules shutdown
HHC01423I Calling termination routines
HHC00101I Thread id 000003ff9577b900, prio 2, name 'Processor CP00' ended
HHC01427I Main storage released
HHC01427I Expanded storage released
HHC01422I Configuration released
HHC01424I All termination routines complete
HHC01425I Hercules shutdown complete
HHC01412I Hercules terminated
HHC00101I Thread id 000003ff9567a900, prio 7, name 'timer_thread' ended
`

Thank you very much! Now i can run VM370 on Linux on z/VM on s390....very nice ;)

Build log as attachment if interested
[hyperion-buildall-2022-03-11.log](https://github.com/wrljet/hercules-helper/files/8231009/hyperion-buildall-2022-03-11.log)

**Comment by wrljet** [comment]
Yes, *run* needs to be defined loosely here.

With my deeply nested virtualized and emulated s390x on which I did this, it took 109 minutes to finish `make` on the zLinux.
I see from your log that it took 1min 36sec on your real hardware.

Bill

**Comment by nix234** [comment]
Yeah, it's really trial and error, some stuff runs wicket fast, other stuff like haskell runs even slower than on my 10yo Workstation.
