### ISSUE TITLE
builds against the wrong branch

### ISSUE THREAD

**Issue by atncsj6h** [wrljet/hercules-helper#26]
IMO 
the build should be done against the develop branch

after the clone of hyperion a 
git checkout develop 
should be done

on apple M1 the master branch does not pass the test suite and crashes 
but it works on high sierra on the intel imac

switched branches and everything works

enrico

**Comment by wrljet** [comment]
Enrico,

Of course there's two ways to look at that.  And I do mostly agree with you.

You can edit `hercules-helper.conf` and uncomment the line to automatically use the `develop` branch.

```
# Git checkout branch for Hyperion
# git_branch_hyperion=develop
```
  to
```
# Git checkout branch for Hyperion
git_branch_hyperion=develop
```

Bill

**Comment by wrljet** [comment]
BTW, M1 works on release branch with Big Sur and Clang 12.

I have been reluctant to upgrade my Mac Mini to their latest OS and Xcode tools.

**Comment by atncsj6h** [comment]
OOPS ...
my bad , I had not noticed the .conf possibility
 

BTW...
what kind of performace do you get on the M1 
IMO something smells fishy 

I jusr ran a quick and dirty comparison 
running the rexxcps.rex script  I get 
on the x86_64 quadcore imac 2.93 ghz ( MID 2010 ) I get around 7600000 clauses per second
on the macmini M1 I get around 26000000 clauses per second
NOT BAD

on the other side   whatever the legacy developer might think
the hercules performance on the apple M1 is less than satisfactory ( PC jargon for 'sucks' )

the mips on the graphical console show that an imac ( mid 2010 ) is faster than the mac mini

the maxrate command gives  more than a 15% difference in favor of the imac 
( x86_64 vs M1 )

for the IPL
mips 69.5 vs. 57.1 
I/O rate 2720 vs. 2410

for the shutdown
mips 77.9 vs. 60.9
I/O rate 520 vs. 190

pretty depressing isnt it ?!

I guess that is the result of all the hand optimization done by the legacy developers  

end of rant

PS
on the imac I have the network configured and I was able to ftp the rexxcpx script
and on the emulated thing I got arond 44000 clauses per second

**Comment by wrljet** [comment]
Enrico,

The only performance benchmark I have, is running an MVS SYSGEN.
And yes, the Mac Mini M1 runs that just a little slower than my not-current i7 PC with VMware Debian 10.

I see I/Os as high as 5000 on the Mac M1, though.

Bill

**Comment by wrljet** [comment]
Switched to `develop` branch some time back, with commit https://github.com/wrljet/hercules-helper/commit/744fa204cce38cc5798dd81c3280c6ef1d24f7e3
