### ISSUE TITLE
Additional packages are compiled with debug info and -O2 flag

### ISSUE THREAD

**Issue by vladkorge** [wrljet/hercules-helper#27]
I've noticed that while the hercules is compiled wiht -O3, the additional packages (the onces that use CMAKE) are compiled with RelWithDebInfo settings and so with -g -O2. 
Can this be fixed pls?

**Comment by wrljet** [comment]
Hi,

I don't recommend -O3, but I will make that configurable.

Bill

**Comment by wrljet** [comment]
Vlad,

This is now configurable.
If you pull down the latest, which as of right now, is https://github.com/wrljet/hercules-helper/commit/710ac67b234580c77dc8f20b587a3d7ebe81b46c

Uncomment the last line in `hercules-helper.conf`.  Then rerun `hyperion-buildall.sh`.
This will use -O3 compiler option.

Just FYI... I have not changes anything in the SDL-Hercules for this.  Hercules-Helper does not use the
"gists" build scheme.  I call CMake directly for each of the extpkgs.

Let me know if it doesn't work for you.

Bill

**Comment by vladkorge** [comment]
Yes, the new parameter is working as expected. Thanks a lot.
