### ISSUE TITLE
Type/revision of Raspberry PI.

### ISSUE THREAD

**Issue by AllardKrings** [wrljet/hercules-helper#28]
Hi,

today I ran the Hyperion-buildall script om two new raspberry pi’s. It could not get a valu for Revision. 

It seems that there is a new version/revision that can be added:

Output from GPIO.RPI_INFO['P1_REVISION']
 3
Output from GPIO.RPI_INFO['RAM']
 8G
Output from GPIO.RPI_INFO['REVISION']
 d03115
Output from GPIO.RPI_INFO['TYPE']
 Pi 4 Model B
Output from GPIO.RPI_INFO['PROCESSOR']
 BCM2711
Output from GPIO.RPI_INFO['MANUFACTURER']
 Sony UK

**Comment by wrljet** [comment]
Are we good-to-go to close this issue?

**Comment by wrljet** [comment]
Closing due to lack of negative response.
