### ISSUE TITLE
Build on debian failure or not?

### ISSUE THREAD

**Issue by N3Cr0N** [wrljet/hercules-helper#3]
Hi,
i have running the build script on debian, i dont no all is fine, i have seen many warnings comes from hyperions code but i think thats ok.

One error i have seen and i dont understand.

on the attached hyperion-buildall-make-check.log in line 300:
```
>>>>> line 83616: Informational message mismatch.
                  Want: HHC17006W MAINSIZE decreased to 2G architectural maximum
                  Got:  HHC02204I ARCHLVL        set to S/370
Test "mainsize check storage size":  25 OK compares.  One failure.
....
Did 324 tests.  1 failed; 323 OK.
```

hyperion-buildall-make-check:
[hyperion-buildall-make-check.log](https://github.com/wrljet/hercules-helper/files/5644863/hyperion-buildall-make-check.log)

Here is the full log:
[hyperion-buildall.log](https://github.com/wrljet/hercules-helper/files/5644872/hyperion-buildall.log)

And can you tell me how i can start hercules?
if i type hercules in the shell the system returns "command not found"

if i compile hercules manual from the source without all extpcks and rexx,
i can start hercules only by typing "hercules" or with the config file syntax  "-f" on the shell, or is my build failed?

thanks for help!

**Comment by wrljet** [comment]
I will answer the "how to start Hercules" question separately.

The "mainsize" test failure is a known issue.  You can read about the cause here:
https://github.com/SDL-Hercules-390/hyperion/issues/330

You can (most likely) ignore that test failure.

Bill

**Comment by wrljet** [comment]
With the most recent commit 443c8ae, the hyperion-buildall.sh will now create
a shell script after the installation completess, that can be used to set the required PATH
and LD_LIBRARY_PATH environment variables.

You can run   `source hercules-setvars.sh`    to set up the env vars.
Then your new Hercules will be in the search path.

Bill
