### ISSUE TITLE
ppc64le not detected as 64-bit system

### ISSUE THREAD

**Issue by racingmars** [wrljet/hercules-helper#30]
Modern POWER systems (POWER8 and later) run the ppc64le Linux machine type, not ppc64. detect_bitness() needs a `-o "$mach" = "ppc64le"` to detect it as a 64-bit machine. (line 1617 of hyperion-buildall.sh).

(I already had Regina Rexx built and installed on my system, but had to make a similar change (add ppc64le) to its configure script to get it to build 64-bit libraries on the system. If it weren't pre-installed, would hercules-helper have downloaded the source and built it? If so, I guess it would need to patch configure to add ppc64le to end up with 64-bit version of Regina too).

**Comment by wrljet** [comment]
Thank you for reporting that problem.  I'll make that correction to the detection.

hyperion-buildall.sh would attempt to build Regina if it's not found to be present.
(unless you tell it not to)

Yes, I guess we will need a patch for Regina.  I made up some patches for other systems that
won't build natively.

I'll work with you on that patch, since I don't have a POWER system on which to test anything.

Bill

**Comment by racingmars** [comment]
Hi Bill -- yep, Regina patch is almost exactly the same. Line 3552 of configure in regina-rexx-3.9.4 needs to have the `-o "$mach" = "ppc64le"` added to it.

**Comment by wrljet** [comment]
Matthew,

I've updated `hyperion-buildall.sh`, and the two existing Regina version patches (3.6 and 3.9.3).
I have no way here to test any of it, though, that I'm aware of.  Fingers are crossed.

Bill

**Comment by racingmars** [comment]
Thanks Bill. I just tried it on a fresh Debian 11 ppc64le installation, and everything worked perfectly. Got a 64-bit Regina and Hyperion.

**Comment by wrljet** [comment]
Cool!

What sort of machines use these POWER ppc64le CPUs?

**Comment by racingmars** [comment]
POWER8 and later are bi-endian, and the Linux world has pretty much abandoned ppc64 in favor of ppc64le (e.g. none of the major distros produce supported ppc64 builds anymore). So any IBM POWER8, POWER9, or POWER10 server running Linux would run ppc64le, as well as anyone with the Raptor Talos workstations.

My machine's an IBM Power S822 server.
