### ISSUE TITLE
Beep before prompt request

### ISSUE THREAD

**Issue by Fish-Git** [wrljet/hercules-helper#32]
I've been doing builds of Hercules on s390x Unbuntu using hercules-helper and it's been working great. However, since it is so incredibly slow _(s390x Unbuntu, not hercules-helper!)_, it is proving to be a PITA to have to babysit it whenever the `--prompts` option is used.

I was thinking it would be nice if hh (hercules-helper) would beep whenever a prompt was issued. This would allow me to not have to closely monitor it for prompts and instead go on to doing something else (rather than have to babysit it). The audible beep would then alert me that it was prompting me for something. (It doesn't have to be a beep. It can be any sound really.)

You could even make the beeping the default with an option to not beep (run silently instead) for those who might not desire it.

I believe such an option would make hh much nicer when used in situations such as mine, where it runs very slow, and might even be a benefit in other situations too where it runs quickly.

What do you think?

**Comment by wrljet** [comment]
Fish, yes that's a good idea!

**Comment by wrljet** [comment]
Fish,

Try this on your Ubuntu VM and let me know if you like the sound presentation?

```
echo -ne '\a'; sleep 0.15; echo -ne '\a'
```

Bill

**Comment by Fish-Git** [comment]
> echo -ne '\a'; sleep 0.15; echo -ne '\a'

[...]
> echo -ne '\a'; sleep 0.15; echo -ne '\a'

Not bad. But 3 slightly closer together beeps sounds better IMO:

`echo -ne '\a'; sleep 0.07; echo -ne '\a'; sleep 0.07; echo -ne '\a'`

Maybe you can make it an environment variable setting? That way people can set it to whatever value they want? After all, my personal likes/dislikes should not rule the day!

And maybe we can somehow incorporate something similar into Hercules itself too? Whenever it detects the guest is waiting for a response it can provide an audible response as well? (or those cases where the user prefers to use the HMC rather than e.g. PuTTY?) If we do that, then the user can actually set (at least on Windows) to *any* .WAV file they want. Even one they record themselves, like "Okay, THAT'S done. NOW what do you want me to do?!" &nbsp;`:)`

* [sounds.zip](https://github.com/wrljet/hercules-helper/files/10528841/sounds.zip)

**Comment by Fish-Git** [comment]
I have my Visual Studio (2008) installation customized to play different sounds whenever a build completes depending on whether it completes with no errors, with warnings, or with errors:

* [build-sounds.zip](https://github.com/wrljet/hercules-helper/files/10528856/build-sounds.zip)

Been using those sounds for probably 20+ years now, on occasion have thought of maybe changing them to Homer Simpson instead (just to be different), but never got around to doing it.

* [Simpsons.zip](https://github.com/wrljet/hercules-helper/files/10528857/Simpsons.zip)

**Comment by wrljet** [comment]
The feature has been added with commit https://github.com/wrljet/hercules-helper/commit/e230cfd490919895bd466641e16df7a10c3c2196

Use `--beep` or `--beeps` to enable it.

Thank you, Fish, for the suggestion.

Bill

**Comment by Fish-Git** [comment]
> The feature has been added with commit [e230cfd](https://github.com/wrljet/hercules-helper/commit/e230cfd490919895bd466641e16df7a10c3c2196)
> 
> Use `--beep` or `--beeps` to enable it.

Cool! Thanks!

Now all I have to do is figure out how to get your changes over to my s390x Ubuntu 18.04 Hercules system. &nbsp;`:)`

> Thank you, Fish, for the suggestion.

You're very welcome, Bill. To reciprocate, I would like to thank _YOU_ for writing Hercules-Helper in the first place!

**Comment by wrljet** [comment]
Fish,

> Now all I have to do is figure out how to get your changes over to my s390x Ubuntu 18.04 Hercules system.  `:)`

Do you not have networking rigged in your zLinux?

**Comment by Fish-Git** [comment]
> Do you not have networking rigged in your zLinux?

Of course. And it works fine too. I just forget where the HH repository is off the top of my head. I'll have to check my notes. I _think_ it's `~/hercules-helper`. Yes?

**Comment by wrljet** [comment]
Yes, should be able to:

```
cd ~/hercules-helper
git pull
```

Of course, a simple `ls` in the home dir will show you where things are.

**Comment by Fish-Git** [comment]
> Of course, a simple `ls` in the home dir will show you where things are.

Duh! I would have eventually figured it out. I was just commenting on the fact that it's been a while since I've messed with that particular Hercules system and so forgot where everything was at. I was kind of hoping for you to have made your current reply several GitHub comments ago. Sheesh. &nbsp;`:)`

**Comment by Fish-Git** [comment]
> The feature has been added with commit [e230cfd](https://github.com/wrljet/hercules-helper/commit/e230cfd490919895bd466641e16df7a10c3c2196)
> 
> Use `--beep` or `--beeps` to enable it.

I just tried it and it works GREAT!

THANK YOU, Bill! &nbsp;`:-)`
