### ISSUE TITLE
Update Hercules Helper for use with zsh on mac

### ISSUE THREAD

**Issue by trigger2k20** [wrljet/hercules-helper#33]
Hi,
any chance to expand the installation script to use, as alternative to bsh, zsh - since it is now the standard shell with macOS ? 

Thanks Trigger2k23

**Comment by trigger2k20** [comment]
Hello Bill,

Looking forward too ! :-) 

PS. Can you also program a possibility to download and integrate the TK4 package ? Reason behind is the install script of TK4 installs it's own Hercules (wich also do not work properly on Apple Silicon due to missing tools - which are hardly obtainable… :-( ) but I would like to have an interaction with your Hercules implementation.

Thank you very much for your effort,
Sascha

**Comment by trigger2k20** [comment]
Hi Bill, since Moshix has promoted your Tool recently https://www.youtube.com/watch?v=NvzbsXTBE1Q i wanted to take the oppotunity and ask when you have time to fix the scripts using zsh...

Thank You, Sascha

**Comment by wrljet** [comment]
Sascha,

It should now detect and know how to set up the .zshrc on macOS.
Give it a try and let me know how it works for you.

Bill

**Comment by trigger2k20** [comment]
Bill,

can confirm it works - see screenshot ! :-) May i suggest that you should change the affected section in your README.md 
Suggestion:

To set the required environment variables after installation, a script will be added to ~/herctest/herc4x/hyperion-init-bash.sh. This will be "sourced" from ~/.bashrc or ~/.zshrc for macOS

To make the newly created Hercules available immediately in the current shell or terminal session, simply source this script with the '.' command:

. ~/herctest/herc4x/hyperion-init-bash.sh
. ~/herctest/herc4x/hyperion-init-zsh.sh

Thanks again ! PS. Does HH also works on a Rasberry PI4 ?
Cheers and Thank you very much
Sascha

![Bildschirmfoto 2023-06-09 um 13 14 20](https://github.com/wrljet/hercules-helper/assets/64564422/6359c648-d34c-40cd-9fe2-c559c3c26f3e)

**Comment by wrljet** [comment]
Sascha,

The README has been updated. Thank you for reminding me.

Yes, this all works on Raspberry Pi.  32- and 64-bit Pi OS, and a few others such as FreeBSD 12.
But they are not frequently tested.

(Occasionally Pi will release an updated circuit board, and I need to add the model number into the script, 
but that doesn't happen too often.  Seems mostly related to supply chain issues and they switch component parts.)

Bill

**Comment by wrljet** [comment]
Sascha,

> PS. Can you also program a possibility to download and integrate the TK4 package ? Reason behind is the install script of TK4 installs it's own Hercules (wich also do not work properly on Apple Silicon due to missing tools - which are hardly obtainable… :-( ) but I would like to have an interaction with your Hercules implementation.

I played with this a bit today on the Mac.  It's not difficult to change the TK4- `start_herc` and `mvs` scripts to work with binaries produced by Hercules-Helper.

I don't want to get involved with a "feature", but I can show you how to do it.

Bill

**Comment by trigger2k20** [comment]
Bill,
thanks i fully understand that you won't get involved ;-) but please show me how to to change the TK4- start_herc and mvs scripts to work with binaries produced by Hercules-Helper.

Beside of that i run your script i found 3 points for a possible modification:
1: i am not quite shure if the zsh setting are considered when starting the hercules-buildall.sh because when starting it mentiones only .bashrc **run  : Add setting environment variables from .bashrc**
2: with the --homebrew option and homebrew installed hercules-buildall.sh does not find autoconf and automake
**Build tools versions:
  autoconf       : /Users/sascha/hercules-helper/hercules-buildall.sh: line 3672: autoconf: command not found
  automake       : /Users/sascha/hercules-helper/hercules-buildall.sh: line 3673: automake: command not found**

i had to install manually via homebrew autoconf and automake - brew install autoXXXX then it finds it
**Build tools versions:
  autoconf       : autoconf (GNU Autoconf) 2.71
  automake       : automake (GNU automake) 1.16.5**

3: you mentioning in readme.md homebrew is installed in /opt and and should be included in the path. on my intel (macos ventura) based mac homebrew is installed in /usr/local not in /opt... but on my m1 (macos ventura) it is installed in /opt so you might rework the statement
**For MacOS and Homebrew, be sure /opt/homebrew/bin appears at the front of your search PATH, so newer packages from Brew override older defaults from MacOS or the Xcode command line tools. (this may only be a requirement for Apple M1 silicon -- to be determined)** 

Thanks Sascha

**Comment by wrljet** [comment]
> Beside of that i run your script i found 3 points for a possible modification:
>
> 1: i am not quite shure if the zsh setting are considered when starting the hercules-buildall.sh because when starting it mentiones only .bashrc **run : Add setting environment variables from .bashrc**

This is just an informational message up front, where it lists the steps to be performed.
It's not dynamic, and just says .bashrc.  I will fix that.

> 2: with the --homebrew option and homebrew installed hercules-buildall.sh does not find autoconf and automake **Build tools versions: autoconf : /Users/sascha/hercules-helper/hercules-buildall.sh: line 3672: autoconf: command not found automake : /Users/sascha/hercules-helper/hercules-buildall.sh: line 3673: automake: command not found**

Again, that is debug information I like to see, but is produced before the actual package checks and installation
is performed. 
 
> i had to install manually via homebrew autoconf and automake - brew install autoXXXX then it finds it **Build tools versions: autoconf : autoconf (GNU Autoconf) 2.71 automake : automake (GNU automake) 1.16.5**

You should not have to do that.  That would be done later, along with all the other actual package checks.

Your `...buildall-2023...log` will show you where it actually checks for the packages.


> 3: you mentioning in readme.md homebrew is installed in /opt and and should be included in the path. on my intel (macos ventura) based mac homebrew is installed in /usr/local not in /opt... but on my m1 (macos ventura) it is installed in /opt so you might rework the statement (also mentioning for mac intel the path /usr/local/homebrew/bin and /usr/local/homebrew/sbin should be in front of the path - which they are not on my intel mac) **For MacOS and Homebrew, be sure /opt/homebrew/bin appears at the front of your search PATH, so newer packages from Brew override older defaults from MacOS or the Xcode command line tools. (this may only be a requirement for Apple M1 silicon -- to be determined)**

Yeah, the documentation always lags behind. :-)
I will improve that topic.

> 
> Thanks if i can help just mention... Sascha

When reporting stuff in future, please always zip up and send me the `...buildlog-2023...log`.  It will show me things you perhaps don't understand or didn't notice.

Bill

**Comment by wrljet** [comment]
Initial request completed with commit: https://github.com/wrljet/hercules-helper/commit/2f2ddf55d0dfcd83512a1693bee7ac7df3567dc8

**Comment by wrljet** [comment]
Assumed fixed/implemented/corrected, but no response for some time.

**Comment by trigger2k20** [comment]
Hello Bill,
great you fixed the issues. Sorry i was rather busy due to work overload.

Thanks,
Sascha
