### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by wahlterh** [wrljet/hercules-helper#35]
Hi. I need your help.

GNU nano 5.4                                                /home/pi/hyperion-buildall.log                                                          
Using logfile: hyperion-buildall-2023-04-17-1.log
Creating build cmds file: /home/pi/build-commands-2023-04-17-1.log
Script version: /home/pi/hercules-helper/hyperion-buildall.sh: v0.9.14-12-ga374fc1

Config file: /home/pi/hercules-helper/hercules-helper.conf

General Options:
  --trace         : false
  --verbose       : true
  --prompts       : true
  --beeps         : false
  --sudo          : false
  --askpass       : false
  --detect-only   : false
  --no-packages   : false
  --no-rexx       : false
  --no-gitclone   : false
  --no-bldlvlck   : false
  --no-autogen    : true
  --no-configure  : false
  --no-clean      : false
  --no-make       : false
  --no-tests      : false
  --no-install    : false
  --no-setcap     : false
  --no-envscript  : false
  --no-bashrc     : false

System information:
  uname -a        : Linux RPi400 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
  uname -m        : aarch64
  uname -p        : unknown
  uname -s        : Linux

System detection:
OS Type          : Linux
Machine Arch     : aarch64
Memory Total (MB): 3794
Memory Free  (MB): 1271
VERSION_ID       : debian
VERSION_ID_LIKE  :
VERSION_PRETTY   : Debian GNU/Linux 11 (bullseye)
VERSION_STR      : 11
OS               : debian variant
OS Version       : 11
*Language         : LANG=sv_SE.UTF-8

Checking for Windows WSL2... nope
Checking for Windows WSL1... nope

Running on Raspberry Pi hardware
Checking for Raspberry Pi... found
Raspberry Pi rev : c03131
CPU count        : 4
/home/pi/hercules-helper/hyperion-buildall.sh: line 1048: RPI_REVISIONS[$RPI_REVCODE]: unbound variable
finish() called, exit status = 1

* I've changed it to EN.UTF.8 but it makes no difference.

**Comment by wrljet** [comment]
I've checked in a change to add that board code [c03131].
No way for me to test that here, but it should work.

Let me know.
Bill

**Comment by wahlterh** [comment]
Thank you.
It works like a charm!
FYI, it is a Pi400.
