### ISSUE TITLE
Hercules helper fails on Pi / Raspberry PiOS

### ISSUE THREAD

**Issue by jeff-snyder** [wrljet/hercules-helper#36]
Hi Bill,

I ran into a couple minor issues today with Hercules Helper I wanted to let you know about.  Nothing major, but maybe unsettling for someone that hasn't used the tool before.

1.  The "Looking for existing Hercules binaries ... please wait ..." step never completes on my Pi.  In looking at the script, there is a find command used to locate prior instances of the Hercules binaries and that apparently doesn't work on the Pi (or at least not on one configured like mine :) ).  I started a build and then went off and did something else; after over 20 minutes, this step was still running.  I commented out the find command in the script and it ran to completion. 

2.  The script refused to add the profile commands to my .bashrc script, even though the previous commands in the script were commented out.  I like to keep the old version around until I'm comfortable with the new one; leaving the old statements as comments in my .bashrc makes switching back easier.  The helper script used to add them no matter what so maybe checking is a good idea, but only checking for "active" statements would probably be better.

I have included a file (console.log) that shows the commands entered to recreate issue 1 and the output from the failed run.  I will also include the log files produced by the script.  Note that I renamed the original hercules-buildall.sh script to hercules-buildall.old.sh when I put in my change, so the included log file is named accordingly.

[extra-info-2023-06-13.log](https://github.com/wrljet/hercules-helper/files/11740386/extra-info-2023-06-13.log)
[hercules-buildall.old-2023-06-13.log](https://github.com/wrljet/hercules-helper/files/11740387/hercules-buildall.old-2023-06-13.log)
[build-commands-2023-06-13.log](https://github.com/wrljet/hercules-helper/files/11740388/build-commands-2023-06-13.log)
[console.log](https://github.com/wrljet/hercules-helper/files/11740389/console.log)

**Comment by wrljet** [comment]
Hi Jeff,

Thank you for the report.  I have not run on the Pi for a while.
I will fire it up and try to reproduce your issues.

 "Looking for existing Hercules binaries ... please wait ..." definitely can take *forever* on some systems.
That is in there to help me debug peoples' problems.  But I guess it's time to remove it.
It can take forever on macOS, also.

Bill

**Comment by wrljet** [comment]
Jeff,

For Pi, I generally run on  a 4B with a USB attached SSD.  I imagine that search for binaries would take a lot longer on an SD card.  So I've removed that and put those few commands into a separate helper script, should it ever be needed.

And I loosened up the checking for existing commands in the shell profile.
I think it will work for you.  Let me know.

Bill

**Comment by jeff-snyder** [comment]
Thanks Bill, that fixed both issues.  I like the warning "note:" about multiple sets of Hercules statements in the .bashrc, that will draw someone's attention to the possibility of duplication.

FYI, the total run time of the build was approximately 10 minutes on my Pi 4B with a USB thumb drive.
