### ISSUE TITLE
Please add support for Linux aarch64 (Oracle Linux Server 8.8)

### ISSUE THREAD

**Issue by philmpv** [wrljet/hercules-helper#37]
Fails due to not supported as output shows below.

Many thanks.

[mvs@instance-20220209-2032 hyperion]$ ~/hercules-helper/hercules-buildall.sh --auto --flavor=sdl-hyperion
Using logfile: hercules-buildall-2023-09-24.log
Creating build cmds file: /home/mvs/hyperion/build-commands-2023-09-24.log
Creating extra diagnostic info file: /home/mvs/hyperion/extra-info-2023-09-24.log
Script version: /home/mvs/hercules-helper/hercules-buildall.sh: v0.9.14-48-g51297c8-dirty

Config file: /home/mvs/hercules-helper/sdl-hyperion.conf

General Options:
  --trace         : false
  --verbose       : true
  --prompts       : false
  --beeps         : false
  --sudo          : false
  --askpass       : false
  --detect-only   : false
  --no-packages   : false
  --no-rexx       : false
  --no-gitclone   : false
  --no-bldlvlck   : false
  --no-autogen    : true
  --no-configure  : false
  --no-clean      : false
  --no-make       : false
  --no-tests      : false
  --no-install    : false
  --no-setcap     : false
  --no-envscript  : false
  --no-bashrc     : false

System information:
  uname -a        : Linux instance-20220209-2032 5.4.17-2136.323.8.2.el8uek.aarch64 #2 SMP Tue Sep 19 23:56:05 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux
  uname -m        : aarch64
  uname -p        : aarch64
  uname -s        : Linux

System detection:
OS Type          : Linux
Machine Arch     : aarch64
Memory Total (MB): 23364
Memory Free  (MB): 22299
VERSION_ID       : ol
VERSION_ID_LIKE  : fedora
VERSION_PRETTY   : Oracle Linux Server 8.8
VERSION_STR      : 8.8
Language         : LANG=en_US.UTF-8

Checking for Windows WSL2... nope
Checking for Windows WSL1... nope

Platform Bitness : 64
[[ error: ]] Your system (Oracle Linux Server 8.8) is not (yet) supported!
finish() called, exit status = 1

**Comment by wrljet** [comment]
Phil,

Please do a `git pull` and try it again.

Thanks for reporting this.  You are our first Oracle Linux user.

Bill

**Comment by philmpv** [comment]
Hi Bill

Many thanks. Yay! Flying the flag for Oracle Cloud (Neoverse-N1 4 cores free tier) - Linux Server 8.8.

Hercules version 4.6.0.10941-SDL-g65c97fd6 master branch incorporating OORexx built successfully.

Successful IPL of Rob Prins TK4 and successful connection via ssh tunnel to port 3270 using  Vista TN3270.

Successful IPL of Rob Prins TK5 and successful connection via ssh tunnel to port 3270 using  Vista TN3270.

A veritable success!

Many thanks for your hard work making it easy to build and install Hyperion.

**Comment by meltdown03** [comment]
I have 16 free cores and 96GB on Oracle, maybe it's just because I'm still in the free trial period? I picked the Ubuntu image though. Did you have trouble with the firewall at all, or are you not using it?

**Comment by philmpv** [comment]
From day one I picked the permanently free maximum specced vm allowed and installed Oracle Linux Server. I am using the firewall but just allowing the minimum port set such as ssh to get as much security through isolation.

**Comment by wrljet** [comment]
For what it's worth, I didn't even notice the "aarch64" in your original issue, and just created an x86 Oracle 8.8 on VMware.
After getting the Oracle Linux aspect added, the existing code must have handled the aarch64 for you.

Bill

**Comment by philmpv** [comment]
Luck must be on your side as I am not sure the package repositories are totally “complete” in comparison to other distributions. Fail2ban doesn’t exist for instance.

**Comment by wrljet** [comment]
That is completely outside the scope of issue discussions here.

**Comment by philmpv** [comment]
Hi Bill

Agreed.  I think we can consider this matter closed.

Phil

**Comment by wrljet** [comment]
Any other trouble building Hercules, don't hesitate to ask for help.

Bill
