### ISSUE TITLE
Set-ExecutionPolicy RemoteSigned not working - Unrestricted works

### ISSUE THREAD

**Issue by arfineman** [wrljet/hercules-helper#38]
Hi Bill,
Thank you for putting this together. It is a life saver for computer illiterates like me. I was able to do a build about a year ago on Windows 10 and was successful. But I tried to build a new one on the same PC and it did not work. After setting the execution-policy to remotesigned, I still got a message from PowerShell it it would not load the Hyperion-Buildall because it is not digitally signed. However, after doing some google searches, I set it to 'unrestricted' and it worked. I thought you may want to mention that in the instructions. 
My question now is that if I want to make a modification to one of the .c modules and recompile, how can I do that ? If at all possible. 
Best regards,

**Comment by wrljet** [comment]
We probably ought to move this to the correct repo.
I'll try to do that now.

**Comment by wrljet** [comment]
You can find the new issue here:  https://github.com/wrljet/hercules-helper-windows/issues/6
