### ISSUE TITLE
Check OS function not working correct: syntax error in expression

### ISSUE THREAD

**Issue by slange-dev** [wrljet/hercules-helper#8]
Hi,
i test your script on CentOS 8 Stream (Desktop Edition) but the first step fails.

uname -a:
Linux NB-777 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**~/hercules-helper/hyperion-buildall.sh --verbose --prompts --sudo 2>&1 | tee ./hyperion-buildall.log**

```
Using logfile hyperion-buildall-2021-01-14-6.log
/home/hercules/hercules-helper/hyperion-buildall.sh: v0.9.0-12-ga1b92fd

Using config file: /home/hercules/hercules-helper/hercules-helper.conf
Config file not found.  Using defaults.

General Options:
TRACE                : false
OPT_VERBOSE          : true
OPT_PROMPTS          : true
OPT_NO_INSTALL       : false
OPT_USESUDO          : true

Configuration:
OPT_BUILD_DIR        : /home/hercules/herctest
OPT_INSTALL_DIR      : /home/hercules/herctest/herc4x
GIT_REPO_HYPERION    : https://github.com/SDL-Hercules-390/hyperion.git
GIT_REPO_GISTS       : https://github.com/SDL-Hercules-390/gists.git
GIT_REPO_EXTPKGS     : https://github.com/SDL-Hercules-390
 
System stats:
OS Type          : Linux
Machine Arch     : x86_64
Memory Total (MB): 15762
Memory Free  (MB): 13476
VERSION_ID       : centos
VERSION_ID_LIKE  : rhel fedora
VERSION_PRETTY   : CentOS Linux 8
VERSION_STR      : 8
We have a CentOS system
VERSION_MAJOR    : package centos
VERSION_MINOR    : release is not installed
Language         : LANG=en_US.UTF-8
 
Checking for Windows WSL1... nope
Checking for Windows WSL2... nope

Step: Check for required packages:  Hit return to continue
/home/hercules/hercules-helper/hyperion-buildall.sh: line 930: [[: package centos: syntax error in expression (error token is "centos")
[1;37m[[ [1;31merror: [1;37m]] [0mCentOS version 6 or earlier found, and not supported
```

**Comment by wrljet** [comment]
Hi,

Thanks for reporting that.

Can you run it again, please, and add the `-t` switch.
Then send me the log files.

Oh, not related, but you don't need the --sudo switch in your case.

Thanks,
Bill

**Comment by slange-dev** [comment]
Hi,
here are the logs with the trace function included.

Kind regards 


~/hercules-helper/hyperion-buildall.sh --verbose --prompts -t 2>&1 | tee ./hyperion-buildall.log

[hyperion-buildall.log](https://github.com/wrljet/hercules-helper/files/5816729/hyperion-buildall.log)
[hyperion-buildall-2021-01-14.log](https://github.com/wrljet/hercules-helper/files/5816730/hyperion-buildall-2021-01-14.log)

**Comment by wrljet** [comment]
OK, it should be working now with CentOS Stream.

Also, you can now use a simpler form.  It will create the log without redirection or the `tee`.

`~/hercules-helper/hyperion-buildall.sh --auto`

Tschüss!
Bill

**Comment by slange-dev** [comment]
Hi,
sorry for the late response, another test with your updated script works fine, no errors no problems in the logs.

Thank you!

Tschuß! ;-)

Sebastian

**Comment by wrljet** [comment]
Cool, thanks!

Bill
